/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dw.solar.base.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SolarMeterInput extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5995371761357682504L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SolarMeterInput\",\"namespace\":\"com.dw.solar.base.avro\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",{\"type\":\"long\",\"java-class\":\"java.lang.Long\"}]},{\"name\":\"meterReadTs\",\"type\":[\"null\",\"string\"]},{\"name\":\"name\",\"type\":[\"null\",\"string\"]},{\"name\":\"usage\",\"type\":{\"type\":\"double\",\"java-class\":\"java.lang.Double\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SolarMeterInput> ENCODER =
      new BinaryMessageEncoder<SolarMeterInput>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SolarMeterInput> DECODER =
      new BinaryMessageDecoder<SolarMeterInput>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SolarMeterInput> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SolarMeterInput> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SolarMeterInput> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SolarMeterInput>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SolarMeterInput to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SolarMeterInput from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SolarMeterInput instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SolarMeterInput fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private Long id;
   private CharSequence meterReadTs;
   private CharSequence name;
   private double usage;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SolarMeterInput() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param meterReadTs The new value for meterReadTs
   * @param name The new value for name
   * @param usage The new value for usage
   */
  public SolarMeterInput(Long id, CharSequence meterReadTs, CharSequence name, Double usage) {
    this.id = id;
    this.meterReadTs = meterReadTs;
    this.name = name;
    this.usage = usage;
  }

  public SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return meterReadTs;
    case 2: return name;
    case 3: return usage;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: id = (Long)value$; break;
    case 1: meterReadTs = (CharSequence)value$; break;
    case 2: name = (CharSequence)value$; break;
    case 3: usage = (Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public Long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'meterReadTs' field.
   * @return The value of the 'meterReadTs' field.
   */
  public CharSequence getMeterReadTs() {
    return meterReadTs;
  }


  /**
   * Sets the value of the 'meterReadTs' field.
   * @param value the value to set.
   */
  public void setMeterReadTs(CharSequence value) {
    this.meterReadTs = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'usage' field.
   * @return The value of the 'usage' field.
   */
  public double getUsage() {
    return usage;
  }


  /**
   * Sets the value of the 'usage' field.
   * @param value the value to set.
   */
  public void setUsage(double value) {
    this.usage = value;
  }

  /**
   * Creates a new SolarMeterInput RecordBuilder.
   * @return A new SolarMeterInput RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new SolarMeterInput RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SolarMeterInput RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new SolarMeterInput RecordBuilder by copying an existing SolarMeterInput instance.
   * @param other The existing instance to copy.
   * @return A new SolarMeterInput RecordBuilder
   */
  public static Builder newBuilder(SolarMeterInput other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for SolarMeterInput instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SolarMeterInput>
    implements org.apache.avro.data.RecordBuilder<SolarMeterInput> {

    private Long id;
    private CharSequence meterReadTs;
    private CharSequence name;
    private double usage;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.meterReadTs)) {
        this.meterReadTs = data().deepCopy(fields()[1].schema(), other.meterReadTs);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.usage)) {
        this.usage = data().deepCopy(fields()[3].schema(), other.usage);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing SolarMeterInput instance
     * @param other The existing instance to copy.
     */
    private Builder(SolarMeterInput other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.meterReadTs)) {
        this.meterReadTs = data().deepCopy(fields()[1].schema(), other.meterReadTs);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.usage)) {
        this.usage = data().deepCopy(fields()[3].schema(), other.usage);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public Long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public Builder setId(Long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'meterReadTs' field.
      * @return The value.
      */
    public CharSequence getMeterReadTs() {
      return meterReadTs;
    }


    /**
      * Sets the value of the 'meterReadTs' field.
      * @param value The value of 'meterReadTs'.
      * @return This builder.
      */
    public Builder setMeterReadTs(CharSequence value) {
      validate(fields()[1], value);
      this.meterReadTs = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'meterReadTs' field has been set.
      * @return True if the 'meterReadTs' field has been set, false otherwise.
      */
    public boolean hasMeterReadTs() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'meterReadTs' field.
      * @return This builder.
      */
    public Builder clearMeterReadTs() {
      meterReadTs = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public Builder setName(CharSequence value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'usage' field.
      * @return The value.
      */
    public double getUsage() {
      return usage;
    }


    /**
      * Sets the value of the 'usage' field.
      * @param value The value of 'usage'.
      * @return This builder.
      */
    public Builder setUsage(double value) {
      validate(fields()[3], value);
      this.usage = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'usage' field has been set.
      * @return True if the 'usage' field has been set, false otherwise.
      */
    public boolean hasUsage() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'usage' field.
      * @return This builder.
      */
    public Builder clearUsage() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SolarMeterInput build() {
      try {
        SolarMeterInput record = new SolarMeterInput();
        record.id = fieldSetFlags()[0] ? this.id : (Long) defaultValue(fields()[0]);
        record.meterReadTs = fieldSetFlags()[1] ? this.meterReadTs : (CharSequence) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (CharSequence) defaultValue(fields()[2]);
        record.usage = fieldSetFlags()[3] ? this.usage : (Double) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SolarMeterInput>
    WRITER$ = (org.apache.avro.io.DatumWriter<SolarMeterInput>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SolarMeterInput>
    READER$ = (org.apache.avro.io.DatumReader<SolarMeterInput>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.id == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.id);
    }

    if (this.meterReadTs == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.meterReadTs);
    }

    if (this.name == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.name);
    }

    out.writeDouble(this.usage);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.id = null;
      } else {
        this.id = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.meterReadTs = null;
      } else {
        this.meterReadTs = in.readString(this.meterReadTs instanceof Utf8 ? (Utf8)this.meterReadTs : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.name = null;
      } else {
        this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
      }

      this.usage = in.readDouble();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.id = null;
          } else {
            this.id = in.readLong();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.meterReadTs = null;
          } else {
            this.meterReadTs = in.readString(this.meterReadTs instanceof Utf8 ? (Utf8)this.meterReadTs : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.name = null;
          } else {
            this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          }
          break;

        case 3:
          this.usage = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










